name: MERN CI/CD Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Backend: install dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # 4️⃣ Backend: run tests
      - name: Run backend tests
        working-directory: backend
        run: npm test

      # 5️⃣ Frontend: install dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # 6️⃣ Frontend: build
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # 7️⃣ Docker: build backend image
      - name: Build backend Docker image
        run: docker build -t mern-backend ./backend

      # 8️⃣ Docker: build frontend image
      - name: Build frontend Docker image
        run: docker build -t mern-frontend ./frontend
